# 1. Create a 3x3x3 array with random values 

In [81]:
import numpy as np
rn = np.random.random((3,3,3))
print(rn)

[[[0.54811333 0.17941384 0.24140813]
  [0.86355697 0.90911114 0.05438949]
  [0.36980551 0.94278025 0.13304953]]

 [[0.73165023 0.90547129 0.75675736]
  [0.40541463 0.34924741 0.88266937]
  [0.02254402 0.57049101 0.81743101]]

 [[0.85321643 0.43738651 0.15501972]
  [0.13690393 0.73169637 0.61239775]
  [0.51488072 0.82019006 0.90145824]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [51]:
import numpy as np
a3 = np.zeros((5,5),dtype=int)
a3[1][0] = 1
a3[2][1] = 2
a3[3][2] = 3
a3[4][3] = 4
print(a3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
import numpy as np
print("Checkerboard pattern:")
cp = np.zeros((8,8),dtype=int)
cp[1::2,::2] = 1
cp[::2,1::2] = 1
print(cp)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [9]:
a1 = np.random.random((5,5))
print(a1)
a1max, a1min = a1.max(), a1.min()
a1 = (a1 - a1min)/(a1max - a1min)
print("-------------------------------------")
print("After normalization:")
print(a1)

[[0.49328035 0.18186451 0.05880834 0.76145891 0.32959031]
 [0.87124982 0.4124186  0.12778474 0.71750981 0.16809716]
 [0.58328496 0.87535365 0.29977206 0.28204056 0.37979391]
 [0.16541957 0.99847391 0.2850974  0.03819548 0.85313075]
 [0.55745542 0.09514917 0.38328697 0.36259935 0.938156  ]]
-------------------------------------
After normalization:
[[0.47390929 0.14961184 0.0214655  0.75318097 0.30344827]
 [0.86751334 0.38970273 0.09329508 0.70741393 0.13527501]
 [0.56763691 0.87178692 0.2723966  0.25393165 0.35572853]
 [0.13248666 1.         0.25711492 0.         0.84864478]
 [0.54073894 0.05930956 0.35936607 0.33782271 0.93718706]]


# 5.  How to find common values between two arrays?

In [12]:
import numpy as np
a1 = np.array([2,4,6,8,9,15])
print("Array1 :",a1)
a2 = [4,8,15]
print("Array2 :",a2)
print("Common values between two arrays:")
print(np.intersect1d(a1, a2))

Array1 : [ 2  4  6  8  9 15]
Array2 : [4, 8, 15]
Common values between two arrays:
[ 4  8 15]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

# 7. Consider two random array A and B, check if they are equal

In [57]:
import numpy as np
a1 = np.random.randint(1,2,3)
a2 = np.random.randint(0,2,3)
a3 = np.allclose(a1,a2)
print(a3)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [20]:
import numpy as np
vector = np.random.random(10)
print(vector)
print("------------------------------------")
vector[vector.argmax()] = 0
print("After replacement:",vector)

[0.94105503 0.61893258 0.80377376 0.51649824 0.09172775 0.44932296
 0.19503929 0.61910538 0.09185661 0.58175734]
------------------------------------
After replacement: [0.         0.61893258 0.80377376 0.51649824 0.09172775 0.44932296
 0.19503929 0.61910538 0.09185661 0.58175734]


# 9. How to print all the values of an array?

In [10]:
import numpy as np
a1 = np.array([2, 3, 4])
for x in a1:
    print(x)

2
3
4


# 10.Subtract the mean of each row of a matrix

In [26]:
a1 = np.array([[3,4],[4,5],[7,8]])
print(a1)
print("---------------------------")
sub_mean = a1 - a1.mean()
print("The sub mean of each row is :\n",sub_mean)

[[3 4]
 [4 5]
 [7 8]]
---------------------------
The sub mean of each row is :
 [[-2.16666667 -1.16666667]
 [-1.16666667 -0.16666667]
 [ 1.83333333  2.83333333]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [28]:
a1 = np.random.random(10)
a2 = a1+1
print(a2)

[1.21731863 1.70436766 1.4284916  1.7543202  1.85919659 1.82479507
 1.5845036  1.39151097 1.53773729 1.81308394]


# 12.How to get the diagonal of a dot product?

In [62]:
a1 = np.random.randint(0,10,(3,3))
print("a1:\n",a1)
a2 = np.random.randint(0,10,(3,3))
print("a2:\n",a2)
a3 = np.diag(np.dot(a1, a2))
print("a3:\n",a3)

a1:
 [[5 6 7]
 [8 7 5]
 [3 1 2]]
a2:
 [[9 8 7]
 [0 9 8]
 [9 6 2]]
a3:
 [108 157  33]


# 13.How to find the most frequent value in an array?

In [64]:
a1 = np.random.randint(0,10,100)
print("a1:\n",a1)
fv = np.bincount(a1).argmax()
print("Freq value:",fv)

a1:
 [3 9 8 8 4 0 4 5 1 8 9 8 0 4 0 6 3 5 2 3 3 3 4 4 5 6 5 2 0 4 3 4 7 6 4 2 8
 7 1 0 8 5 3 7 9 7 5 2 9 8 5 3 6 7 2 0 8 8 5 2 9 6 3 6 2 6 9 6 1 4 1 7 5 0
 2 1 9 8 5 4 6 7 3 5 8 9 8 9 5 9 3 9 9 9 3 9 0 5 4 8]
Freq value: 9


# 14.How to get the n largest values of an array

In [74]:
a1 = np.arange(100)
print("a1:\n",a1)
np.random.shuffle(a1)
n = 10
a2 = a1[np.argsort(a1)[-n:]]
print("a2:\n",a2)

a1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
a2:
 [90 91 92 93 94 95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [80]:
a1 = np.array([("How are", 4.2, 3),
              ("You", 6.6, 2)])
a2 = np.core.records.fromarrays(a1.T,
                               names ='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(a2)

[(b'How are', 4.2, 3) (b'You', 6.6, 2)]
